[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4.29"
env_logger = "0.11.8"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
